### ISSUE TITLE
mariadb keeps restarting

### ISSUE THREAD

**Issue by kklepper** [nazar-pc/docker-webserver#16] opened 2016-02-23 23:33 UTC
Hi Nazar,

I try to understand and implement your extensive setup. It is the most complete I found yet.

I never ran across consul or ceph, so I don't understand what they do. 

So far I can spawn a load balancer in front of an NGINX-PHP (web) module connected to a MySQL or MariaDB database which itself is connected to a data container pointing to a real database on a Digital Ocean Droplet, then start a number of web instances and prove that both the load balancer and the database work correctly (provided I use version 1 of docker-compose, as tutum/haproxy does not work with version 2 yet).

Using your example, I see that examplecom_mariadb_1 keeps restarting, so I commented the automatic restart in docker-compose.yml, only to see that this container exits with 1. The log file only shows the password.

If I understand your scripts correctly, you project everything to your /data subdirectory within the container, which isn't of much use if the container isn't running.

Any ideas?

Thanks a lot anyway.

**Comment by nazar-pc** [comment] 2016-02-24 01:33
Consul is used for DNS and storing Ceph configuration if it is used. Ceph is used for CephFS, distributed file system (crucial for distributed apps when using Docker Swarm), but Ceph image is experimental currently.

Did you try basic example?
Advanced examples are currently blocked by #11 because of breaking changes introduced in Docker 1.10.

MariaDB restarting was caused by recent change in base image: https://github.com/docker-library/mariadb/commit/032647e59d4ce5405eb2db79f70364a1cf05ed56
It should be fixed in 495b532, try to pull fresh image and it should work fine now.
Sorry about confusion and thanks for the report!

**Comment by kklepper** [comment] 2016-02-24 12:17
Yes, I tried only the basic example. Will have another look today. Thanks so far.

**Comment by nazar-pc** [comment] 2016-02-24 12:24
I should work now, just pull latest image

**Comment by kklepper** [comment] 2016-02-24 17:43
Great! Alas, I can't test, because I am dumb, now I get 

```
wp@ubuntu-512mb-fra1-01:~/nazar/docker-webserver/example.com$ sudo docker-compose up -d
ERROR: Service "data" mounts volumes from "example.com", which is not the name of a service or container.
```

and I don't know what this means or what to do. What happened? I didn't get this error the first time. Can you help me once again?

**Comment by nazar-pc** [comment] 2016-02-24 18:20
You just skipped first step from tutorial:

```
docker run --name example.com nazarpc/webserver:data
```

You need this named container in order to store your data permanently.

**Comment by kklepper** [comment] 2016-02-24 18:31
Great, thanks a lot! Works like a charm! Or not?

```
wp@ubuntu-512mb-fra1-01:~/kklepper/docker-webserver/example.com$ sudo docker run --name example.com nazarpc/webserver:data
[sudo] password for wp:
wp@ubuntu-512mb-fra1-01:~/kklepper/docker-webserver/example.com$ sudo docker-compose up -d
Creating examplecom_data_1
Creating examplecom_mariadb_1
Creating examplecom_ssh_1
Creating examplecom_logrotate_1
Creating examplecom_php_1
Creating examplecom_nginx_1
wp@ubuntu-512mb-fra1-01:~/kklepper/docker-webserver/example.com$ sudo docker-compose ps
         Name                       Command                 State                     Ports
-----------------------------------------------------------------------------------------------------------
examplecom_data_1        sh                               Exit 0
examplecom_logrotate_1   /bin/sh -c watch --no-titl ...   Up
examplecom_mariadb_1     /webserver-entrypoint.sh m ...   Restarting   3306/tcp
examplecom_nginx_1       /webserver-entrypoint.sh n ...   Up           443/tcp, 46.101.104.194:8070->80/tcp
examplecom_php_1         /webserver-entrypoint.sh p ...   Up           9000/tcp
examplecom_ssh_1         /webserver-entrypoint.sh         Up           46.101.104.194:8091->22/tcp
```

What is wrong here? Or what am I to do?

**Comment by nazar-pc** [comment] 2016-02-24 18:46
Did you pull latest mariadb image `docker-compose pull`?
Can you provide output of `docker-compose logs mariadb`?

**Comment by kklepper** [comment] 2016-02-24 22:47
No, I didn't. Perfect. Thank you very much.

Next problem: nginx gives me a 403 Forbidden. How is this setup meant to work?

mariadb seems to need more memory (Digital Ocean 512 MB). Cannot start innodb, restarts. Will try again with more memory soon.
.

**Comment by nazar-pc** [comment] 2016-02-24 22:50
You need to put some files under `/data/nginx/www`, it might be empty initially, thus 403 because you are not allowed to see directory listing.

**Comment by kklepper** [comment] 2016-02-24 23:11
Ok, I see, thank you.

As for MariaDB, I changed galera.cnf to (MyIsam support is in beta)

```
[mysqld]
# Enforcing mandatory settings
wsrep_provider=/usr/lib/galera/libgalera_smm.so
binlog_format=ROW
bind-address=0.0.0.0
#default_storage_engine=InnoDB
default_storage_engine=MyIsam
#innodb_autoinc_lock_mode=2
#innodb_doublewrite=1
#innodb_flush_log_at_trx_commit=0
#transaction_isolation=READ-COMMITTED
wsrep_on=ON
wsrep_replicate_myisam=ON
skip_innodb
```

but still innodb is invoked:

```
wp@ubuntu-512mb-fra1-01:~/nazar/docker-webserver/example.com$ sudo docker logs examplecom_mariadb_1
MySQL root password (from /data/mysql/root_password): QvgCSMhO39bPqxLRfko7yr9JVrTdJD
2016-02-24 23:07:18 140178895366080 [Note] mysqld (mysqld 10.1.11-MariaDB-1~jessie) starting as process 1 ...
2016-02-24 23:07:18 140178895366080 [Note] WSREP: Read nil XID from storage engines, skipping position init
2016-02-24 23:07:18 140178895366080 [Note] WSREP: wsrep_load(): loading provider library '/usr/lib/galera/libgalera_smm.so'
2016-02-24 23:07:18 140178895366080 [Note] WSREP: wsrep_load(): Galera 25.3.12(r3516) by Codership Oy <info@codership.com> loaded successfully.
2016-02-24 23:07:18 140178895366080 [Note] WSREP: CRC-32C: using hardware acceleration.
2016-02-24 23:07:18 140178895366080 [Note] WSREP: Found saved state: 0fab2050-db47-11e5-a383-f63c9e28a3ef:-1
2016-02-24 23:07:18 140178895366080 [Note] WSREP: Passing config to GCS: base_dir = /var/lib/mysql_local/; base_host = 172.17.0.2; base_port = 4567; cert.log_conflicts = no; debug = no; evs.auto_evict = 0; evs.delay_margin = PT1S; evs.delayed_keep_period = PT30S; evs.inactive_check_period = PT0.5S; evs.inactive_timeout = PT15S; evs.join_retrans_period = PT1S; evs.max_install_timeouts = 3; evs.send_window = 4; evs.stats_report_period = PT1M; evs.suspect_timeout = PT5S; evs.user_send_window = 2; evs.view_forget_timeout = PT24H; gcache.dir = /var/lib/mysql_local/; gcache.keep_pages_size = 0; gcache.mem_size = 0; gcache.name = /var/lib/mysql_local//galera.cache; gcache.page_size = 128M; gcache.size = 128M; gcs.fc_debug = 0; gcs.fc_factor = 1.0; gcs.fc_limit = 16; gcs.fc_master_slave = no; gcs.max_packet_size = 64500; gcs.max_throttle = 0.25; gcs.recv_q_hard_limit = 9223372036854775807; gcs.recv_q_soft_limit = 0.25; gcs.sync_donor = no; gmcast.segment = 0; gmcast.version = 0; pc.announce_timeout = PT3S; pc.checksum = false; pc.ignore_quorum = false; pc.ig
2016-02-24 23:07:18 140178579953408 [Note] WSREP: Service thread queue flushed.
2016-02-24 23:07:18 140178895366080 [Note] WSREP: Assign initial position for certification: -1, protocol version: -1
2016-02-24 23:07:18 140178895366080 [Note] WSREP: wsrep_sst_grab()
2016-02-24 23:07:18 140178895366080 [Note] WSREP: Start replication
2016-02-24 23:07:18 140178895366080 [Note] WSREP: Setting initial position to 00000000-0000-0000-0000-000000000000:-1
2016-02-24 23:07:18 140178895366080 [Note] WSREP: protonet asio version 0
2016-02-24 23:07:18 140178895366080 [Note] WSREP: Using CRC-32C for message checksums.
2016-02-24 23:07:18 140178895366080 [Note] WSREP: backend: asio
2016-02-24 23:07:18 140178895366080 [Warning] WSREP: access file(/var/lib/mysql_local//gvwstate.dat) failed(No such file or directory)
2016-02-24 23:07:18 140178895366080 [Note] WSREP: restore pc from disk failed
2016-02-24 23:07:18 140178895366080 [Note] WSREP: GMCast version 0
2016-02-24 23:07:18 140178895366080 [Note] WSREP: (5a489855, 'tcp://0.0.0.0:4567') listening at tcp://0.0.0.0:4567
2016-02-24 23:07:18 140178895366080 [Note] WSREP: (5a489855, 'tcp://0.0.0.0:4567') multicast: , ttl: 1
2016-02-24 23:07:18 140178895366080 [Note] WSREP: EVS version 0
2016-02-24 23:07:18 140178895366080 [Note] WSREP: gcomm: connecting to group 'my_wsrep_cluster', peer ''
2016-02-24 23:07:18 140178895366080 [Note] WSREP: start_prim is enabled, turn off pc_recovery
2016-02-24 23:07:18 140178895366080 [Note] WSREP: Node 5a489855 state prim
2016-02-24 23:07:18 140178895366080 [Note] WSREP: view(view_id(PRIM,5a489855,1) memb {
        5a489855,0
} joined {
} left {
} partitioned {
})
2016-02-24 23:07:18 140178895366080 [Note] WSREP: save pc into disk
2016-02-24 23:07:18 140178895366080 [Note] WSREP: gcomm: connected
2016-02-24 23:07:18 140178895366080 [Note] WSREP: Changing maximum packet size to 64500, resulting msg size: 32636
2016-02-24 23:07:18 140178895366080 [Note] WSREP: Shifting CLOSED -> OPEN (TO: 0)
2016-02-24 23:07:18 140178895366080 [Note] WSREP: Opened channel 'my_wsrep_cluster'
2016-02-24 23:07:18 140178521843456 [Note] WSREP: New COMPONENT: primary = yes, bootstrap = no, my_idx = 0, memb_num = 1
2016-02-24 23:07:18 140178895366080 [Note] WSREP: Waiting for SST to complete.
2016-02-24 23:07:18 140178521843456 [Note] WSREP: Starting new group from scratch: 5a4b6b9f-db4b-11e5-b2cc-527229860f4d
2016-02-24 23:07:18 140178521843456 [Note] WSREP: STATE_EXCHANGE: sent state UUID: 5a4c1c97-db4b-11e5-9b3e-c73f8b3b2870
2016-02-24 23:07:18 140178521843456 [Note] WSREP: STATE EXCHANGE: sent state msg: 5a4c1c97-db4b-11e5-9b3e-c73f8b3b2870
2016-02-24 23:07:18 140178521843456 [Note] WSREP: STATE EXCHANGE: got state msg: 5a4c1c97-db4b-11e5-9b3e-c73f8b3b2870 from 0 ()
2016-02-24 23:07:18 140178521843456 [Note] WSREP: Quorum results:
        version    = 3,
        component  = PRIMARY,
        conf_id    = 0,
        members    = 1/1 (joined/total),
        act_id     = 0,
        last_appl. = -1,
        protocols  = 0/7/3 (gcs/repl/appl),
        group UUID = 5a4b6b9f-db4b-11e5-b2cc-527229860f4d
2016-02-24 23:07:18 140178521843456 [Note] WSREP: Flow-control interval: [16, 16]
2016-02-24 23:07:18 140178521843456 [Note] WSREP: Restored state OPEN -> JOINED (0)
2016-02-24 23:07:18 140178895051520 [Note] WSREP: New cluster view: global state: 5a4b6b9f-db4b-11e5-b2cc-527229860f4d:0, view# 1: Primary, number of nodes: 1, my index: 0, protocol version 3
2016-02-24 23:07:18 140178895366080 [Note] WSREP: SST complete, seqno: 0
2016-02-24 23:07:18 140178521843456 [Note] WSREP: Member 0.0 () synced with group.
2016-02-24 23:07:18 140178521843456 [Note] WSREP: Shifting JOINED -> SYNCED (TO: 0)
2016-02-24 23:07:19 140178895366080 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2016-02-24 23:07:19 140178895366080 [Note] InnoDB: The InnoDB memory heap is disabled
2016-02-24 23:07:19 140178895366080 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2016-02-24 23:07:19 140178895366080 [Note] InnoDB: Memory barrier is not used
2016-02-24 23:07:19 140178895366080 [Note] InnoDB: Compressed tables use zlib 1.2.8
2016-02-24 23:07:19 140178895366080 [Note] InnoDB: Using Linux native AIO
2016-02-24 23:07:19 140178895366080 [Note] InnoDB: Using SSE crc32 instructions
2016-02-24 23:07:19 140178895366080 [Note] InnoDB: Initializing buffer pool, size = 256.0M
InnoDB: mmap(276824064 bytes) failed; errno 12
2016-02-24 23:07:19 140178895366080 [ERROR] InnoDB: Cannot allocate memory for the buffer pool
2016-02-24 23:07:19 140178895366080 [ERROR] Plugin 'InnoDB' init function returned error.
2016-02-24 23:07:19 140178895366080 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2016-02-24 23:07:19 140178895366080 [Note] Plugin 'FEEDBACK' is disabled.
2016-02-24 23:07:19 140178895366080 [ERROR] Unknown/unsupported storage engine: InnoDB
2016-02-24 23:07:19 140178895366080 [ERROR] Aborting
```

Do I overlook something?

**Comment by nazar-pc** [comment] 2016-02-24 23:17
`galera.cnf` is only part of configuration related to replication, there are few more files, probably, you need to modify them as well. But 512 MiB should be enough to run database I think.

**Comment by kklepper** [comment] 2016-02-24 23:32
Ok, I'll try it. Must be late for you, it certainly is for me. Good night, till tomorrow. Again, thanks a lot.

**Comment by kklepper** [comment] 2016-02-25 16:54
Hi again. I could not find any other cfg for mariadb (where could I look for it?), so I turned to AWS and set up an EC2 instance. Compared to Digital Ocean, that was a real mess and took me hours, without my experience with DO probably even more. 

Anyway MariaDB is running fine on InnoDB, so I conclude that this definitely was an out of memory problem. 

Finally I got:

```
Starting examplecom_data_1
examplecom_mariadb_1 is up-to-date
Starting examplecom_ssh_1
ERROR: Cannot start container a3e880ee23fad24a02241b2beeb5ed53106185d4418a446980108377e9aabb0a: failed to create endpoint examplecom_ssh_1 on network bridge: Error starting userland proxy: listen tcp 54.93.172.63:8095: bind: cannot assign requested address
```

I concluded that this can be fixed by studying AWS security options, so I  commented this out. Next I got 

```
Status: Downloaded newer image for nazarpc/webserver:nginx
Creating examplecom_nginx_1
ERROR: Cannot start container 666aee79ea365f1eb2fa528768c0147823885a2f168d10214c68de0d04da5a69: failed to create endpoint examplecom_nginx_1 on network bridge: Error starting userland proxy: listen tcp 54.93.172.63:8090: bind: cannot assign requested address
```

No idea here.

**Comment by nazar-pc** [comment] 2016-02-25 17:10
Configs are available inside container, they're from MariaDB package, default from distributive. You can start MariaDB at least once (even if it fails eventually) and then go to SSH or directly to data container and modify configuration in `/data/mysql/config` directory.

Mentioned errors are not about images in this repo, try to search for them somewhere, I have no idea what are they, seems something AWS-specific.

**Comment by kklepper** [comment] 2016-02-25 17:15
Ok, thanks a lot. Makes sense.

**Closed as completed** 2016-08-20 05:51 UTC
